//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMC2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class bprofile
    {
        public long id { get; set; }
        public string bname { get; set; }
        public string tinumber { get; set; }
        public string baddress { get; set; }
        public string bnature { get; set; }
        public string dtinumber { get; set; }
        public string blisencenumber { get; set; }
    }
}
