//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMC2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public long id { get; set; }
        public string category { get; set; }
        public string label { get; set; }
        public string description { get; set; }
        public Nullable<double> dishcost { get; set; }
        public Nullable<double> dishprice { get; set; }
        public Nullable<long> available { get; set; }
        public string loggedby { get; set; }
    }
}
