//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMC2021
{
    using Microsoft.EntityFrameworkCore;
    using System;
    //using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSDB2Entities : DbContext
    {
        public POSDB2Entities()
          //  : base("name=POSDB2Entities")
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //NOTE! CHANGE THIS PATH PAG PACKING NA!
            //optionsBuilder.UseSqlite(@"Data Source=C:\Users\Frei\source\repos\BMC2021\POSDB.sqlite");
            // data source = "|DataDirectory|\bin\POSDB.sqlite"
            // optionsBuilder.UseSqlite(@"Data Source=|DataDirectory|\db\POSDB.sqlite");

            string baseDir = AppDomain.CurrentDomain.BaseDirectory;

            //if "bin" is present, remove all the path starting from "bin" word
            if (baseDir.Contains("bin"))
            {
                int index = baseDir.IndexOf("bin");
                baseDir = baseDir.Substring(0, index);
            }

            //String interpolation to reach the right path
            optionsBuilder.UseSqlite($"Data Source={baseDir}\\bin\\POSDB2.sqlite");


        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
           // throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_users> admin_users { get; set; }
        public virtual DbSet<bprofile> bprofile { get; set; }
        public virtual DbSet<current_user> current_user { get; set; }
        //public virtual DbSet<Lisensya> Lisensya { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<sales_customers> sales_customers { get; set; }
        public virtual DbSet<sales_peritem> sales_peritem { get; set; }
        public virtual DbSet<sales_pending_orders> sales_pending_orders { get; set; }
    }
}
