//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMC2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public long id { get; set; }
        public Nullable<long> repeat { get; set; }
        public string date { get; set; }
        public string title { get; set; }
    }
}
