//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMC2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_pending_orders
    {
        public long id { get; set; }
        public string category { get; set; }
        public string label { get; set; }
        public Nullable<long> qty { get; set; }
        public string dateorderplaced { get; set; }
        public string customername { get; set; }
        public Nullable<long> discount { get; set; }
        public Nullable<double> price { get; set; }
        public string deliverydate { get; set; }
        public Nullable<double> tprice { get; set; }
        public string loggedby { get; set; }
        public string notes { get; set; }
    }
}
